import Link from "next/link";
import { StarRatingDisplay } from "@/components/StarRating";
import GigPreview from "./GigPreview";

export type CardGig = { id: string; title: string; description: string; category: string; price_ngn: number; is_ai_assisted: boolean; seller_profiles: { display_name: string; verification_status: string } | null };
export type CardRating = { average_rating: number; review_count: number };
const LABELS: Record<string, string> = { development: "Development", design: "Design", marketing: "Marketing", writing: "Writing", ai_assisted: "AI-assisted" };
function LockIcon() { return <svg width="11" height="11" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" aria-hidden="true"><rect x="3" y="11" width="18" height="10" rx="2" /><path d="M7 11V7a5 5 0 0 1 10 0v4" /></svg>; }
export default function GigCard({ gig, rating }: { gig: CardGig; rating?: CardRating }) {
  const seller = gig.seller_profiles?.display_name ?? "Unknown seller";
  const verified = gig.seller_profiles?.verification_status === "approved";
  return <Link href={`/gigs/${gig.id}`} className="gm-card group block overflow-hidden rounded-xl border border-line bg-paper"><div className="gm-preview relative aspect-[16/10]"><div className="gm-preview-inner absolute inset-0"><GigPreview category={gig.category} seed={gig.id} /></div>{gig.is_ai_assisted && <span className="absolute left-3 top-3 rounded-full bg-[#1C1B18]/75 px-2 py-0.5 text-[10px] font-semibold tracking-wide text-[#F5F2EC] backdrop-blur-sm">AI-assisted</span>}</div><div className="p-4 sm:p-5"><p className="text-[10px] font-semibold uppercase tracking-[.14em] text-slate">{LABELS[gig.category] ?? gig.category}</p><h3 className="mt-1.5 line-clamp-2 font-display text-[15px] font-bold leading-snug text-bone">{gig.title}</h3><div className="mt-3 flex items-center justify-between gap-2"><span className="flex min-w-0 items-center gap-1.5 text-xs text-slate"><span className="h-2 w-2 shrink-0 rounded-full bg-ember/70" /><span className="truncate">{seller}</span>{verified && <span aria-label="Verified seller" className="text-ember">✓</span>}</span>{rating && rating.review_count > 0 && <span className="shrink-0"><StarRatingDisplay average={rating.average_rating} count={rating.review_count} size={11} /></span>}</div><div className="mt-4 flex items-end justify-between border-t border-line pt-3"><span><span className="block text-[10px] uppercase tracking-wide text-slate">Price</span><span className="font-mono text-[15px] font-semibold text-bone">₦{gig.price_ngn.toLocaleString()}</span></span><span className="flex items-center gap-1.5 text-[11px] text-slate"><LockIcon />Protected<span className="gm-arrow ml-0.5 text-ember" aria-hidden="true">→</span></span></div></div></Link>;
}